from fpdf import FPDF
import os

class PDFExporter:
    def export(self, topic, paper_data, filename="research_paper.pdf"):
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # --- TITLE PAGE ---
        pdf.set_font("Helvetica", 'B', 24)
        pdf.cell(0, 60, "", ln=True) # Space
        pdf.multi_cell(0, 15, txt=f"Research Paper: {topic.upper()}", align='C')
        
        pdf.set_font("Helvetica", 'I', 12)
        pdf.cell(0, 20, txt="Generated by AI Research Agent", ln=True, align='C')
        pdf.cell(0, 10, txt="Date: 2026", ln=True, align='C')
        
        pdf.add_page()
        
        # --- CONTENT ---
        pdf.set_font("Helvetica", size=12)
        
        # CrewAI returns data in a dict or string, we handle both
        content = ""
        if isinstance(paper_data, dict):
            # Take everything in the dictionary
            content = "\n\n".join([str(v) for v in paper_data.values()])
        else:
            content = str(paper_data)

        # Basic Markdown Cleanup for PDF
        content = content.replace("#", "").replace("**", "") 
        
        # Writing to PDF with proper encoding
        pdf.multi_cell(0, 10, txt=content.encode('latin-1', 'ignore').decode('latin-1'))
        
        # Save File
        output_path = os.path.join(os.getcwd(), filename)
        pdf.output(output_path)
        return output_path